### ISSUE TITLE
appkey怎么获取?每个人都不一样?

### ISSUE THREAD

**Issue by weituotian** [hiyouga/bilibiliapi#1]
一脸懵逼

**Comment by hiyouga** [comment]
你好啊，刚刚看到信息抱歉了
appkey官方一开始是给发放的，后来全部成了内部使用，现在appkey只能通过一些bilibili的程序来找了

**Comment by weituotian** [comment]
原来如此, 感谢啊,解决了我的问题
![Uploading image.png…]()
